name: Testcode
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.2.0
  
      - name: Run MATLAB script
        uses: Codes-Exe/run-command@v1.0.3
        with:
          command: matlab -batch "run('test.m')"
